// Code generated by MockGen. DO NOT EDIT.
// Source: authenticator.go
//
// Generated by this command:
//
//	mockgen -source authenticator.go -destination authenticator_generated.go -package auth . Authenticator
//

// Package auth is a generated GoMock package.
package auth

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticator is a mock of Authenticator interface.
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
	isgomock struct{}
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator.
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance.
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockAuthenticator) Authenticate(w http.ResponseWriter, r *http.Request) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", w, r)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockAuthenticatorMockRecorder) Authenticate(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuthenticator)(nil).Authenticate), w, r)
}

// AuthenticateOnControlPlane mocks base method.
func (m *MockAuthenticator) AuthenticateOnControlPlane(r *http.Request) (ControlPlaneAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateOnControlPlane", r)
	ret0, _ := ret[0].(ControlPlaneAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateOnControlPlane indicates an expected call of AuthenticateOnControlPlane.
func (mr *MockAuthenticatorMockRecorder) AuthenticateOnControlPlane(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateOnControlPlane", reflect.TypeOf((*MockAuthenticator)(nil).AuthenticateOnControlPlane), r)
}
