// Code generated by MockGen. DO NOT EDIT.
// Source: control_plane_agent.go
//
// Generated by this command:
//
//	mockgen -source control_plane_agent.go -destination control_plane_agent_generated.go -package auth . ControlPlaneAgent
//

// Package auth is a generated GoMock package.
package auth

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockControlPlaneAgent is a mock of ControlPlaneAgent interface.
type MockControlPlaneAgent struct {
	ctrl     *gomock.Controller
	recorder *MockControlPlaneAgentMockRecorder
	isgomock struct{}
}

// MockControlPlaneAgentMockRecorder is the mock recorder for MockControlPlaneAgent.
type MockControlPlaneAgentMockRecorder struct {
	mock *MockControlPlaneAgent
}

// NewMockControlPlaneAgent creates a new mock instance.
func NewMockControlPlaneAgent(ctrl *gomock.Controller) *MockControlPlaneAgent {
	mock := &MockControlPlaneAgent{ctrl: ctrl}
	mock.recorder = &MockControlPlaneAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControlPlaneAgent) EXPECT() *MockControlPlaneAgentMockRecorder {
	return m.recorder
}

// GetClientID mocks base method.
func (m *MockControlPlaneAgent) GetClientID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetClientID indicates an expected call of GetClientID.
func (mr *MockControlPlaneAgentMockRecorder) GetClientID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientID", reflect.TypeOf((*MockControlPlaneAgent)(nil).GetClientID))
}

// GetOrganizationID mocks base method.
func (m *MockControlPlaneAgent) GetOrganizationID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetOrganizationID indicates an expected call of GetOrganizationID.
func (mr *MockControlPlaneAgentMockRecorder) GetOrganizationID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationID", reflect.TypeOf((*MockControlPlaneAgent)(nil).GetOrganizationID))
}

// GetScopes mocks base method.
func (m *MockControlPlaneAgent) GetScopes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScopes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetScopes indicates an expected call of GetScopes.
func (mr *MockControlPlaneAgentMockRecorder) GetScopes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScopes", reflect.TypeOf((*MockControlPlaneAgent)(nil).GetScopes))
}

// HasScope mocks base method.
func (m *MockControlPlaneAgent) HasScope(scope string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasScope", scope)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasScope indicates an expected call of HasScope.
func (mr *MockControlPlaneAgentMockRecorder) HasScope(scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasScope", reflect.TypeOf((*MockControlPlaneAgent)(nil).HasScope), scope)
}

// Subject mocks base method.
func (m *MockControlPlaneAgent) Subject() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subject")
	ret0, _ := ret[0].(string)
	return ret0
}

// Subject indicates an expected call of Subject.
func (mr *MockControlPlaneAgentMockRecorder) Subject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subject", reflect.TypeOf((*MockControlPlaneAgent)(nil).Subject))
}
