name: Default
on:
  merge_group:
  push:
    branches:
      - releases/*
      - main
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Dirty:
    runs-on: "shipfox-4vcpu-ubuntu-2404"
    steps:
      - uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0
      - name: Setup Env
        uses: ./.github/actions/env
      - run: >
          nix develop --impure --command just pre-commit
      - name: Check for uncommitted changes
        shell: bash
        run: |
          hasChanged=$(git status --porcelain)
          if (( $(echo ${#hasChanged}) != 0 )); then
            git status
            git diff
            echo "There are changes in the repository"
            exit 1
          fi

  Tests:
    runs-on: "shipfox-4vcpu-ubuntu-2404"
    steps:
      - uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0
      - name: Setup Env
        uses: ./.github/actions/env
      - run: >
          nix develop --impure --command just tests
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v6.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
