name: Default
on:
  merge_group:
  push:
    branches:
      - releases/*
      - main
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Ci:
    runs-on: "formance-runner"
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: Auto-Merge Dependabot PRs
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        uses: fastify/github-action-merge-dependabot@v3
        with:
          use-github-auto-merge: 'true'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Setup Env
        uses: ./.github/actions/env
      - run: >
          earthly
          --allow-privileged 
          --secret SPEAKEASY_API_KEY=$SPEAKEASY_API_KEY
          ${{ contains(github.event.pull_request.labels.*.name, 'no-cache') && '--no-cache' || '' }}
          +ci
        env:
          SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}
      - name: Get changed files
        id: changed-files
        shell: bash
        run: |
          hasChanged=$(git status --porcelain) 
          if (( $(echo ${#hasChanged}) != 0 )); then
            git status
            echo "There are changes in the repository"
            exit 1
      - name: Validate Dependabot PR
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: |
          gh pr review $PR_URL --approve -b "Auto approve dependencies bump PR"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
